### ISSUE TITLE
Using Extract Steps in Reaper

### ISSUE THREAD

**Issue by carriebrinkley** [Datastillery/scd_epics#80]
Implement a way to have a series of steps as part of the exraction versus declaring them as specific keys on the dataset definition.  Currently when we have attempted to implement new dataset types (soap, authorization, post) we have had to change the dataset definition in a way which requires a migration of existing datasets or just changes to a wider scope of the application.  By refactoring to use a list of steps following the same abstraction as sources and destinations, new types of steps can be developed by SCOS and the community without worrying about legacy data. 
See example
https://github.com/inhindsight/hindsight/blob/master/apps/extract_http/lib/extract/http/get.ex 
(L)

**Comment by JulieMaterni** [comment]
Benefits SOAP and Self-Service features.
